on:
  push:
    branches:
      - main
      - dev

stages:
    - build
    - test

before_script:
    - docker info

build_container:
    stage: build
    script:
    - docker build -t results-vis-image .