stages:
    - build
    - test

before_script:
    - docker info

build_container:
    stage: build
    rules:
       - if: $CI_COMMIT_BRANCH == "main"
    script:
    - docker image rm results-vis-image
    - docker build -t results-vis-image .

unit_tests:
    stage: test
    image: python:3.9
    before_script:
    - apt-get update -q -y
    - apt-get install -y python-pip
    - pip install -r requirements.txt
    script:
    - pytest -v
