stages:
    - build
    - test

before_script:
    - docker info

build_container:
    stage: build
    rules:
       - if: $CI_COMMIT_BRANCH != main
    script:
    - docker build -t results-vis-image .